create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
GRANT ALL PRIVILEGES ON *.* TO 'riblila'@'172.20.144.1' IDENTIFIED BY 'blank' WITH GRANT OPTION;create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
