create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
GRANT ALL PRIVILEGES ON *.* TO 'riblila'@'172.30.0.1' IDENTIFIED BY 'blank' WITH GRANT OPTION;create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence product_seq start with 1 increment by 50 nocache;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
GRANT ALL PRIVILEGES ON *.* TO 'riblila'@'192.168.144.1' IDENTIFIED BY 'blank' WITH GRANT OPTION; create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23), id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (price float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (price float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (price float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (price float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (price float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (price float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (price float(23) not null, amount float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (price float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (price float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, price float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (price float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (price float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, price float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (price float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (price float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, price float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (price float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (price float(23) not null, id bigint not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
INSERT INTO webshop.product (price, id, image_url, name, description, short_name) VALUES (60000, 1, 'assets/img/btc.png', 'Bitcoin', 'Bitcoin sfkodskfodsk sd jfkjsdk kdsjfk ljdlkfj dlskfj', 'BTC');
INSERT INTO webshop.product (price, id, image_url, name, description, short_name) VALUES (2700, 2, 'assets/img/eth.png', 'Ethereum', 'Ethereum sfkodskfodsk sd jfkjsdk kdsjfk ljdlkfj dlskfj', 'ETH');
INSERT INTO webshop.product (price, id, image_url, name, description, short_name) VALUES (160, 3, 'assets/img/sol.png', 'Solana', 'Solana sfkodskfodsk sd jfkjsdk kdsjfk ljdlkfj dlskfj', 'SOL');
INSERT INTO webshop.product (price, id, image_url, name, description, short_name) VALUES (0.8, 4, 'assets/img/ondo.png', 'Ondo', 'Ondo sfkodskfodsk sd jfkjsdk kdsjfk ljdlkfj dlskfj', 'ONDO');
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create sequence cart_seq start with 1 increment by 50 nocache;
create sequence favorites_seq start with 1 increment by 50 nocache;
create sequence product_seq start with 1 increment by 50 nocache;
create table cart (amount float(23) not null, price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table favorites (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
create table product (price float(23) not null, id bigint not null, short_name varchar(10) not null, image_url varchar(25) not null, name varchar(50) not null, description varchar(250) not null, primary key (id)) engine=InnoDB;
